language: java

services:
  - mysql
  - mongodb
  - redis-server

jdk:
  - openjdk8

before_install:
  - echo "CREATE USER 'tpuser'@'%' IDENTIFIED BY 'tpuser';\nGRANT ALL PRIVILEGES ON *.* TO 'tpuser'@'%' WITH GRANT OPTION;\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql --user=tpuser --password=tpuser -e 'CREATE DATABASE IF NOT EXISTS joits;'
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'


#script:
#  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install jacoco:report coveralls:report
  
after_success:
  - mvn clean test jacoco:report coveralls:report
